interface ACTION_TYPES  {
    INCREMENT: String,
    CHANGE_THEME: String,
}

const ACTION_TYPES = {
    INCREMENT: 'INCREMENT',
    CHANGE_THEME: 'CHANGE_THEME',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
};

export { ACTION_TYPES };